name: ID tests

on:
  push:
    paths:
      - "lib/games.js"
      - ".github/workflows/id-tests.yml" # This action
  pull_request:
    paths:
      - "lib/games.js"
      - ".github/workflows/id-tests.yml" # This action
  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - uses: Swatinem/rust-cache@v2
    # TODO: Change to official repo once merged
    - run: cargo install --git https://github.com/Douile/rust-gamedig.git --branch feat/id-test-cli gamedig-id-tests
    - name: Run ID tests
      run: node tools/run-id-tests.js